# Generated by Django 3.1.3 on 2021-09-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vender_Details',
            fields=[
                ('vd_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('vd_vender_name', models.TextField(default=None, max_length=5000)),
                ('vd_email_id', models.TextField(default=None, max_length=5000)),
                ('vd_mob_number', models.TextField(default=None, max_length=5000)),
                ('vd_created_at', models.DateTimeField(auto_now_add=True)),
                ('vd_last_modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
