# Generated by Django 3.1.3 on 2021-09-01 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aao_vender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender_details',
            name='vd_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vender_details_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
