# Generated by Django 3.1.3 on 2021-09-01 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aao_vender', '0003_auto_20210901_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vender_Details',
            fields=[
                ('vd_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('vd_mob_number', models.TextField(default=None, max_length=5000)),
                ('vd_created_at', models.DateTimeField(auto_now_add=True)),
                ('vd_last_modified_on', models.DateTimeField(auto_now=True)),
                ('vd_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vender_details_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='vender_master',
        ),
    ]
