# Generated by Django 3.1.3 on 2021-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aao_vender', '0004_auto_20210901_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender_details',
            name='vd_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
