# Generated by Django 3.1.3 on 2021-09-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aao_vender', '0005_vender_details_vd_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender_details',
            name='vd_aao_balance',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vender_details',
            name='vd_aao_user',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
