# Generated by Django 3.1.3 on 2021-09-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aao_vender', '0007_auto_20210901_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender_details',
            name='vd_per_user_price',
            field=models.PositiveIntegerField(default=100, null=True),
        ),
    ]
