# Generated by Django 3.1.3 on 2021-09-01 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aao_vender', '0008_vender_details_vd_per_user_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aoo_User_Details',
            fields=[
                ('aud_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('aud_username', models.TextField(default=None, max_length=5000)),
                ('aud_email', models.TextField(default=None, max_length=5000)),
                ('aud_mobile_number', models.TextField(default=None, max_length=20)),
                ('aud_subsc_package', models.TextField(default=None, max_length=10)),
                ('aud_created_at', models.DateTimeField(auto_now_add=True)),
                ('aud_last_modified_on', models.DateTimeField(auto_now=True)),
                ('aud_is_active', models.BooleanField(default=True)),
                ('aud_vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoo_user_details_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
