# Generated by Django 3.1.3 on 2021-09-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aao_vender', '0009_aoo_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoo_user_details',
            name='aud_subsc_package',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
