# Generated by Django 3.1.3 on 2021-09-01 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aao_vender', '0010_auto_20210902_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoo_user_details',
            name='aud_end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aoo_user_details',
            name='aud_start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
