# Generated by Django 3.1.3 on 2021-09-02 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aao_vender', '0011_auto_20210902_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aoo_User_Order_Details',
            fields=[
                ('auod_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('auod_subsc_package', models.PositiveIntegerField(default=1, null=True)),
                ('auod_start_date', models.DateTimeField(blank=True)),
                ('auod_end_date', models.DateTimeField(blank=True)),
                ('auod_created_at', models.DateTimeField(auto_now_add=True)),
                ('auod_last_modified_on', models.DateTimeField(auto_now=True)),
                ('auod_is_active', models.BooleanField(default=True)),
                ('auod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoo_user_order_details_user', to='aao_vender.aoo_user_details')),
                ('auod_vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aoo_user_order_details_vender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='vender_details',
            name='vd_mob_number',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='Vender_Transection_Details',
            fields=[
                ('vtd_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('vtd_debit', models.PositiveIntegerField(default=0)),
                ('vtd_total_remaining', models.PositiveIntegerField(default=0)),
                ('vtd_created_at', models.DateTimeField(auto_now_add=True)),
                ('vtd_last_modified_on', models.DateTimeField(auto_now=True)),
                ('vtd_is_active', models.BooleanField(default=True)),
                ('vtd_trans_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vender_transection_details_trans_for', to='aao_vender.aoo_user_order_details')),
                ('vtd_vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vender_transection_details_vender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Ading_Credit',
            fields=[
                ('adc_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('adc_credit_amount', models.PositiveIntegerField(default=0, null=True)),
                ('adc_created_at', models.DateTimeField(auto_now_add=True)),
                ('adc_last_modified_on', models.DateTimeField(auto_now=True)),
                ('adc_is_active', models.BooleanField(default=True)),
                ('adc_vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ading_credit_vender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
