# Generated by Django 3.2.7 on 2021-09-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aao_vender', '0012_auto_20210902_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender_details',
            name='vd_plan_subscribe',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
