# Generated by Django 3.2.7 on 2021-09-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aao_vender', '0013_vender_details_vd_plan_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender_details',
            name='vd_api_key',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='vender_details',
            name='vd_api_secrate',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
