# Generated by Django 3.2.7 on 2021-09-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aao_vender', '0014_auto_20210906_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender_details',
            name='vd_aao_balance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vender_details',
            name='vd_per_user_price',
            field=models.FloatField(default=100, null=True),
        ),
    ]
